global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.18.0.90:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.17.0.1:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['172.18.0.91:8080']

  - job_name: 'spacemesh'
    static_configs:
      - targets: ["172.18.0.101:10001"]
        labels:
          name: 'node01'

      - targets: ["172.18.0.102:10002"]
        labels:
          name: 'node02'