# This file assumes you are using an already existing network.
# You can create a new one or update it to use an existing one
version: "2"
services:
  post_service01: # Repeat for as many sets of postdata
    image: spacemeshos/post-service:v0.6.5 # Update with latest
    container_name: post_service01
    volumes:
      - /media/postdata/postdata01:/postdata
      - /home/hakedev/certs:/certs
    command:
      - '--dir'
      - '/postdata'
      - '--address'
      - 'https://<YOUR NODE_SERVICE IP>:<PORT>'
      - '--ca-cert'
      - '/certs/ca.crt'
      - '--cert'
      - '/certs/client.crt'
      - '--key'
      - '/certs/client.key'
      - '--threads'
      - '6'
    environment:
      - TZ=America/Phoenix
    networks:
      spacenet:
        ipv4_address: 172.18.0.101

  post_service02: # Repeat for as many sets of postdata
    image: spacemeshos/post-service:v0.6.5 # Update with latest
    container_name: post_service02
    volumes:
      - /media/postdata/postdata02:/postdata
      - /home/hakedev/certs:/certs
    command:
      - '--dir'
      - '/postdata'
      - '--address'
      - 'https://<YOUR NODE_SERVICE IP>:<PORT>'
      - '--ca-cert'
      - '/certs/ca.crt'
      - '--cert'
      - '/certs/client.crt'
      - '--key'
      - '/certs/client.key'
      - '--threads'
      - '6'
    environment:
      - TZ=America/Phoenix
    networks:
      spacenet:
        ipv4_address: 172.18.0.102

networks:
  spacenet:
    external: true
    name: spacemesh-poet_spacenet